services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
